### ISSUE TITLE
AbstractString not defined error when running code on Julia 0.4

### ISSUE THREAD

**Issue by viveksck** [sbos/AdaGram.jl#13]
Hi,
Thanks for releasing the code for Adaptive Skipgram. I am facing an issue running the code:  where I get an error saying AbstractString not defined. Any ideas !

Thanks.

vvkulkarni@darwin:~/.julia/v0.4/AdaGram$ ./train.s-h 
ERROR: AbstractString not defined
 in include at boot.jl:238
at /home/vvkulkarni/.julia/v0.4/AdaGram/train.jl:573

**Comment by viveksck** [comment]
Never mind. Had a mis configuration

**Comment by Bitseat** [comment]
It would help me if you added how you fixed it.
