### ISSUE TITLE
build.sh fails when running without clang

### ISSUE THREAD

**Issue by napsternxg** [sbos/AdaGram.jl#16]
I tried installing the package without clang but the build.sh files fails. The reason being that the if condition in the build file is incorrect. I have made the required change and was able to install it successfully. I will send a pull request.

**Comment by dilaratorunoglu** [comment]
Hello,
I am having problem running build.sh too.  When I was installing the AdaGram I write "Pkg.build("AdaGram")" it gives me an error of "could not spawn,  `../build.sh: unknown error <UNKNOWN> while loading DIRECTORY, in expression starting line 1". 
And I used your solution changed the build.sh but it still gives me same error. 
Do you have any idea? Thank you.
