### ISSUE TITLE
superlib not found

### ISSUE THREAD

**Issue by mojesty** [sbos/AdaGram.jl#20]
Like in [this issue](https://github.com/sbos/AdaGram.jl/issues/4), I face the same problem even when using run.sh:

> ./run.sh train.jl --window=5 --workers=3 --alpha=0.1 tokenized_sentences.txt adagram_dict.txt test_model.p

> ERROR: LoadError: On worker 2:
error compiling var_update_z!: could not load library "superlib"
dlopen(superlib.dylib, 1): image not found

Julia 0.5 macosx

**Comment by KPilnacek** [comment]
Hey there :),
I ran into the very same issue some time ago. As far as I remember, I put a link to library `superlib.so`, which is in AdaGram.jl/lib to /usr/lib.
In the end, I also used julia 0.4.5-3 as the new version was incompatible.

Julia 0.4.5-3, Ubuntu 16.04

**Comment by ClaudeCoulombe** [comment]
Greetings,

I just want to add for newbies like me that you should execute build.sh in order to get the superlib.dylib in the AdaGram.jl/lib folder. After you can just start the Julia shell with run.sh

I hope this can help someone else
