### ISSUE TITLE
Training from 

### ISSUE THREAD

**Issue by glicerico** [sbos/AdaGram.jl#21]
Hi, thanks a lot for offering AdaGram.

- How can one train a model from many different files? Does one have to provide a single pre-procesed file with all text appended together?

- Also, do you offer some clustering algorithm inside AdaGram, like word2vec does?

Thanks

**Comment by lopuhin** [comment]
@glicerico out of interest, which clustering algorithms does word2vec provide? do you mean pre-processing that finds collocations, or something else?

**Comment by glicerico** [comment]
@lopuhin No, I mean clustering after word embedding. They provide K-means activated by a flag when running the code. You can see an example in their demo-classes.sh
From their code website:

Word clustering

The word vectors can be also used for deriving word classes from huge data sets. This is achieved by performing K-means clustering on top of the word vectors. The script that demonstrates this is ./demo-classes.sh. The output is a vocabulary file with words and their corresponding class IDs, such as:

carnivores 234 carnivorous 234 cetaceans 234 cormorant 234 coyotes 234 crocodile 234 crocodiles 234 crustaceans 234 cultivated 234 danios 234 . . . acceptance 412 argue 412 argues 412 arguing 412 argument 412 arguments 412 belief 412 believe 412 challenge 412 claim 412

**Comment by glicerico** [comment]
So @lopuhin , I'm guessing you don't know how to train a model using different files?

**Comment by lopuhin** [comment]
@glicerico I'm not an AdaGram.jl developer, but I'm pretty sure that if you want to use the command line interface, you must have a single file.
And I don't think AdaGram.jl has any clustering algorithms, but you can extract the sense vectors and do clustering yourself.

**Comment by glicerico** [comment]
@lopuhin I just submitted a pull request that adds clustering functionality to AdaGram
https://github.com/sbos/AdaGram.jl/pull/22

**Comment by sbos** [comment]
Hi @glicerico,

The code we provide supports only files as inputs, but it should be fairly simple to adapt it for generic streams.
If you manage to implement this, please do send a pull request!

@lopuhin Thanks for the pull request, I will try to review it soon. I unfortunately don't have much time to support AdaGram as it was a research project during my PhD.

**Comment by lopuhin** [comment]
@sbos thanks! For the record, it's @glicerico 's pull request :)

And thanks for putting the code on github, it's great and really useful!

**Comment by sbos** [comment]
@lopuhin you are welcome
@glicerico Sorry for confusing your authorship! What version of julia you are using BTW?

**Comment by glicerico** [comment]
@sbos No worries. I'm using Julia v0.4.5.
My first question is related to being able to "add learning" to a model. Say that you train a model with some corpus, and later you want to add another corpus to it without reprocessing the first one. But I think I see this is not possible from the way the algorithm itself works.

**Comment by sbos** [comment]
@glicerico Well, the training algorithm is based on stochastic gradient optimization which means that you could continue training on a different file. 
But you might need to do something against catastrophic forgetting and generally think about adaptive learning rates for different words.
