### ISSUE TITLE
Is it possible to get an idea of the recommended training parameters?

### ISSUE THREAD

**Issue by ClaudeCoulombe** [sbos/AdaGram.jl#23]
Is it possible to get an idea of the generally recommended parameters used to train models (only those that are not the default setting)?

For example, DIM = 300, ALPHA = 0.2, MIN-FREQ = 20, SENSE-THRESHOLD = 1e-17

I'm particularly interested to know the parameters that were used to train the huang_super_300D_0.2_min20_hs_t1e-17.model model

**Comment by sbos** [comment]
Hello Claude,

Yes with these parameters you should be good, the most sensitive parameter is alpha, if you get too many senses discovered, you should set it to a lower value, otherwise - increase it.
