### ISSUE TITLE
What's the second element of the tuple returned by the nearest_neighbors() function?

### ISSUE THREAD

**Issue by ClaudeCoulombe** [sbos/AdaGram.jl#26]
I have a simple question? I've briefly checked out the source code but I can't figure the meaning of the second element (a small integer), of the tuple returned by the nearest_neighbors() function?

What can I use it for?

`julia> nearest_neighbors(vm, dict, "apple", 1, 10)
10-element Array{(Any,Any,Any),1}:

("almond", **1**, 0.70396507f0)
("cherry", **2**, 0.69193166f0)  
("plum", **1**, 0.690269f0)     
("apricot", **1**, 0.6882005f0)  
("orange", **4**, 0.6739181f0)
("pecan", **1**, 0.6662803f0)
("pomegranate", **1**, 0.6580653f0)
("blueberry", **1**, 0.6509351f0)
("pear", **1**, 0.6484747f0) 
("peach", **1**, 0.6313036f0) `

**Comment by sbos** [comment]
That's the number of a word sense that was used to compute the similarity

вт, 29 авг. 2017 г. в 4:59, Claude Coulombe <notifications@github.com>:

**Comment by ClaudeCoulombe** [comment]
Great! In this way, this number gives and idea of the polysemy or at the contrary the specificity of the word returned. Thank you.
