### ISSUE TITLE
Disambiguation out of vocabulary words

### ISSUE THREAD

**Issue by alexanderpanchenko** [sbos/AdaGram.jl#4]
Now any out of vocabulary word causes an error:

```
julia> disambiguate(vm, dict, "python", split("tigris python molurus molurus reptile sanctuary albicans pakistan mnp python jamesonii jamesonii ordinatus coluber boaeformis python molurus"))
ERROR: key not found: "ordinatus"
 in disambiguate at /Users/alex/.julia/v0.3/AdaGram/src/util.jl:259 (repeats 2 times)
```

An expected behaviour: out of vocabulary words are filtered out.

**Comment by sbos** [comment]
This not an actual bug :) Otherwise you could provide a word important for the correct disambiguation which is silently ignored as unknown.

**Comment by alexanderpanchenko** [comment]
but normally you need to filter yourself these unknown words anyway, so why just not to provide an extra option to the disambiguate function that would do it for you? just a matter of improving user-friendliness :-)

**Comment by mojesty** [comment]
Well, I still have the same problem even when using run.sh:

> ./run.sh train.jl --window=5 --workers=3 --alpha=0.1 tokenized_sentences.txt adagram_dict.txt test_model.p

> ERROR: LoadError: On worker 2:
error compiling var_update_z!: could not load library "superlib"
dlopen(superlib.dylib, 1): image not found

Julia 0.5 macosx
