### ISSUE TITLE
Disambiguate can't load the lib.

### ISSUE THREAD

**Issue by buriy** [sbos/AdaGram.jl#5]
julia> disambiguate(vm, dict, "apple", split("cell phone"))
ERROR: error compiling var_update_z!: could not load module superlib: superlib: cannot open shared object file: No such file or directory
 in var_update_z! at /home/user/.julia/v0.3/AdaGram/src/gradient.jl:93
 in disambiguate at /home/user/.julia/v0.3/AdaGram/src/util.jl:248
 in disambiguate at /home/user/.julia/v0.3/AdaGram/src/util.jl:259 (repeats 2 times)

I guess I need to add this lib to DL_LIBRARY_PATH myself, but please add this to the documentation.

**Comment by sbos** [comment]
It's almost in the documentation, for simplicity I recommend using run.sh to run julia. You may refer to `run.sh` to see what exactly to pass to the interpreter
