### ISSUE TITLE
Support for Julia 0.4

### ISSUE THREAD

**Issue by buriy** [sbos/AdaGram.jl#7]
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:581
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:612
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:7
in anonymous at /home/buriy/.julia/v0.4/ArgParse/src/ArgParse.jl:612
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at deprecated.jl:73
 [inlined code] from deprecated.jl:694
 in require at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 88
WARNING: replacing module ArrayViews
WARNING: replacing module ArrayViews
WARNING: Method definition iscontiguous(Array) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38.
WARNING: Method definition iscontiguous(DenseArray) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37.
WARNING: Method definition iscontiguous(Array) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38.
WARNING: Method definition iscontiguous(DenseArray) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37.
WARNING: replacing module ArrayViews
WARNING: replacing module ArrayViews
WARNING: Method definition iscontiguous(Array) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38.
WARNING: Method definition iscontiguous(DenseArray) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37.
WARNING: Method definition iscontiguous(Array) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:38.
WARNING: Method definition iscontiguous(DenseArray) in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37 overwritten in module ArrayViews at /home/buriy/.julia/v0.4/ArrayViews/src/common.jl:37.
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/buriy/.julia/v0.4/AdaGram/train.jl:92
Building dictionary... WARNING: int64(s::AbstractString) is deprecated, use parse(Int64,s) instead.
 in depwarn at deprecated.jl:73
 in int64 at deprecated.jl:50
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:9
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:24
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: int64(s::AbstractString) is deprecated, use parse(Int64,s) instead.
 in depwarn at deprecated.jl:73
 in int64 at deprecated.jl:50
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:9
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:24
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in depwarn at deprecated.jl:73
 in int32 at deprecated.jl:50
 in build_huffman_tree at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:41
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:91
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in depwarn at deprecated.jl:73
 in int32 at deprecated.jl:50
 in build_huffman_tree at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:57
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:91
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in depwarn at deprecated.jl:73
 in int32 at deprecated.jl:50
 in pop_initialize! at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:49
 in build_huffman_tree at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:61
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:91
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in depwarn at deprecated.jl:73
 in int32 at deprecated.jl:50
 in path at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:29
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: uint8(x::AbstractFloat) is deprecated, use round(UInt8,x) instead.
 in depwarn at deprecated.jl:73
 in uint8 at deprecated.jl:50
 in convert_huffman_tree at /home/buriy/.julia/v0.4/AdaGram/src/softmax.jl:77
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:92
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: float32(x) is deprecated, use Float32(x) instead.
 in depwarn at deprecated.jl:73
 in float32 at deprecated.jl:50
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:107
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: float32(x) is deprecated, use Float32(x) instead.
 in depwarn at deprecated.jl:73
 in float32 at deprecated.jl:50
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:108
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: push!(t::Associative,key,v) is deprecated, use setindex!(t,v,key) instead.
 in depwarn at deprecated.jl:73
 in push! at deprecated.jl:50
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:25
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
WARNING: push!(t::Associative,key,v) is deprecated, use setindex!(t,v,key) instead.
 in depwarn at deprecated.jl:73
 in push! at deprecated.jl:50
 in call at /home/buriy/.julia/v0.4/AdaGram/src/AdaGram.jl:25
 in read_from_file at /home/buriy/.julia/v0.4/AdaGram/src/util.jl:30
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 98
Done!
WARNING: float64(x) is deprecated, use Float64(x) instead.
 in depwarn at deprecated.jl:73
 in float64 at deprecated.jl:50
 in inplace_train_vectors! at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:119
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 107
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:64
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:67
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
WARNING: isblank(s::AbstractString) is deprecated, use all((c->begin 
            c == ' ' || c == '\t'
        end),s) instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in producer at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:22
while loading no file, in expression starting on line 0
WARNING: isblank(s::AbstractString) is deprecated, use all((c->begin 
            c == ' ' || c == '\t'
        end),s) instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in producer at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:22
while loading no file, in expression starting on line 0
    From worker 2:  64000 words read, 743789/305658269
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:64
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:67
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:64
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\t' instead.
 in depwarn at deprecated.jl:73
 in isblank at deprecated.jl:50
 in align at /home/buriy/.julia/v0.4/AdaGram/src/textutil.jl:67
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:133
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
while loading no file, in expression starting on line 0
ERROR: LoadError: On worker 2:
UndefVarError: subtract! not defined
 in inplace_train_vectors! at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:35
 in anonymous at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:144
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
 in remotecall_fetch at multi.jl:731
 in call_on_owner at multi.jl:776
 in inplace_train_vectors! at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:158
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/buriy/.julia/v0.4/AdaGram/train.jl, in expression starting on line 107
WARNING: Forcibly interrupting busy workers
fatal error on 5: ERROR: InterruptException:
make: **\* [vec/ru-news3/norm.model] Error 1

**Comment by sbos** [comment]
Oh, thanks for the report. I thought that I fixed all the warnings as I could import AdaGram on julia 0.5-dev, but it seems that it requires further work. 

Some of the warnings are really fixed though, just do `Pkg.checkout("AdaGram")`
Let me know if you want to make a pull request with fixes of others.

**Comment by buriy** [comment]
Warnings are fine, fatal errors are not :)

ERROR: LoadError: On worker 2:
UndefVarError: subtract! not defined
in inplace_train_vectors! at /home/buriy/.julia/v0.4/AdaGram/src/gradient.jl:35

Also I believe I used the latest version to get this output...

**Comment by buriy** [comment]
Btw:
latest version doesn't work with Julia 0.3:
ERROR: AbstractString not defined
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/buriy/.julia/v0.3/AdaGram/src/AdaGram.jl, in expression starting on line 18
while loading /home/buriy/.julia/v0.3/AdaGram/train.jl, in expression starting on line 88
make: **\* [vec/ru-news5/norm.model] Error 1

**Comment by buriy** [comment]
The easiest approach is to mark commits with tags related to target julia version ,
So I suggest to tag previous commit with "julia-0.3" tag (because the latest one is broken with both julia v0.3 and v0.4)

**Comment by buriy** [comment]
The easiest approach is to mark commits with tags related to target julia version ,
So I suggest to tag previous commit with "julia-0.3" tag (because the latest one is broken with both julia v0.3 and v0.4)

**Comment by sbos** [comment]
The code should run correctly on julia v0.4 now.
