### ISSUE TITLE
unicode support?

### ISSUE THREAD

**Issue by arspin** [sbos/AdaGram.jl#9]
On _any_ input file with unicode (i.e. utf-8 text in Russian) the default train.sh gives:

ERROR: LoadError: On worker 2:
UnicodeError: invalid character index
 in yieldto at ./task.jl:71
 in wait at ./task.jl:371
 in schedule_and_wait at task.jl:352
 in consume at task.jl:259
 in read_words at [...].julia/v0.4/AdaGram/src/textutil.jl:126
 in anonymous at [...].julia/v0.4/AdaGram/src/gradient.jl:136
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
 in remotecall_fetch at multi.jl:731
 in call_on_owner at multi.jl:776
 in inplace_train_vectors! at [...].julia/v0.4/AdaGram/src/gradient.jl:158
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading [...]AdaGram.jl/train.jl, in expression starting on line 105

Since Julia language is new to me, I'm wondering maybe I can fix this behaviour without patching the AdaGram code? Because it looks like I have to fix looped_word_iterator at src/textutil.jl:26, do_work at src/gradient.jl:24 and maybe somewhere else. Please help :)

**Comment by arspin** [comment]
Now a quick fix of looped_word_iterator at src/textutil.jl:26 that works (added 'try/catch' block):

``` julia
function looped_word_iterator(f::IO, start_pos::Int64, end_pos::Int64)
    function producer()
        while true
            try
                w = readuntil(f, ' ')
                if length(w) < 1 break end
                w = w[1:end-1]
                if !adagram_isblank(w)
                    produce(w)
                end
                if position(f) >= end_pos seek(f, start_pos) end
            catch UnicodeError
            end
        end
    end
    return Task(producer)
end
```

I can make a pull request with this code, but not sure is it the best possible way of dealing with this problem

**Comment by sbos** [comment]
Awesome, thanks! Maybe you'd like to add this as a pull request?

**Comment by arspin** [comment]
pull request to master?

**Comment by sbos** [comment]
Yes, master branch is fine.

пн, 2 нояб. 2015 г. в 14:48, arspin notifications@github.com:

**Comment by ArmanKabiri** [comment]
Hi @sbos and @arspin ,
After the commit for Compatibility with julia v1.1, the above-mentioned issue with Unicode characters is back. I check the src/textutil.jl and noticed that the try catch block is missing.

After trying to add the try catch block, I get errors as follows:

```
ERROR: LoadError: LoadError: syntax: cannot goto label "_STATE_1" inside try/catch block
Stacktrace:
 [1] include at ./boot.jl:326 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /home/arman73k/.julia/packages/AdaGram/bGnM5/src/AdaGram.jl:1
 [5] top-level scope at none:0
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:328 [inlined]
 [11] eval(::Expr) at ./client.jl:404
 [12] top-level scope at ./none:3
in expression starting at /home/arman73k/.julia/packages/AdaGram/bGnM5/src/textutil.jl:21
in expression starting at /home/arman73k/.julia/packages/AdaGram/bGnM5/src/AdaGram.jl:149
```

I could not see the call of goto in any part of the code and do not know why this error occurs and how to fix it.

Do you have any idea of how to add exception handling to this part of the code?

**Comment by ArmanKabiri** [comment]
Hi,

Though I have not able to fix the code, I tackled the issue indirectly. What I did was that I transformed the corpus file to indexes using the dictionary that is made using utils/dictionary.sh. More specifically, I replaced each word in the corpus by its index. So, instead of having a corpus of Unicode characters, I have a corpus of numbers. After the model is trained, I transferred them back to the original words.

Contact me if you need the transformation code.
Arman73k@gmail.com
